FEAT: client docker image

diff --git a/client/dockerfile b/client/dockerfile
--- a/client/dockerfile
+++ b/client/dockerfile
@@ -1,23 +1,58 @@
-# Use an official Node runtime as a parent image
-FROM node:13
+FROM node:18-alpine AS base
 
-# Set the working directory in the container
-WORKDIR /usr/src/app
+# 1. Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 
-# Copy package.json and package-lock.json to the working directory
-COPY package*.json ./
+WORKDIR /app
 
-# Install app dependencies
-RUN npm install
+# Install dependencies based on the preferred package manager
+COPY package.json npm.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f npm.lock ]; then npm --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then npm global add pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Bundle app source
+
+# 2. Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-
-# Build the Next.js app
+# This will do the trick, use the corresponding env file for each environment.
+# COPY .env.production.sample .env.production
 RUN npm run build
 
-# Expose the port that your app will run on
+# 3. Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV=production
+
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/public ./public
+COPY --from=builder --chown=nextjs:nodejs /app/package.json /app/npm* /app/pnpm* ./
+COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
+COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+
+
+USER nextjs
+
 EXPOSE 3000
 
-# Define the command to run your app
+ENV PORT 3000
+ENV HOSTNAME localhost
+
 CMD ["npm", "start"]
